[tool.poetry]
name = "gtfs-rt-producer-data"
version = "0.1.0"
description = "A package for handling Avro schema data"
authors = ["Your Name"]
license = "MIT"
packages = [ { include = "gtfs_rt_producer_data", from="src" } ]

[tool.poetry.dependencies]
python = "<4.0,>=3.10"
dataclasses-json = "^0.6.7"

[tool.poetry.dev-dependencies]
pylint = "^4.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"